
WIN_WIDTH = 1600
WIN_HEIGHT = 900
WIN_SIZE = (WIN_WIDTH, WIN_HEIGHT)

# количество частиц окружения, например звезды
ENVIRONMENT_PARTICLE_AMOUNT = 100
ENVIRONMENT_PARTICLE_MAX_SIZE = 10
ENVIRONMENT_PARTICLE_MIN_SIZE = 1

FPS = 60

GAME_NAME = 'Space War'
